import type { Metadata } from "next";

import { jakartaSans, afacadFlux } from "@/fonts/fonts";

import "./globals.css";

import { cn } from "@/lib/utils";

import { Navbar } from "@/components/layout/navigation";
import { Footer } from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          afacadFlux.variable,
          jakartaSans.variable,
          "antialiased font-display",
        )}
      >
        <div className="flex flex-col min-h-screen">
          <Navbar />
          <main className="flex-1">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
